/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 05-dub-2022 18:31:12 				*/
/*  DBMS       : SQLite 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE [Address]
(
	[AddressId] INTEGER NOT NULL,
	[Name] TEXT NOT NULL,
	[State] TEXT NOT NULL,
	[Town] TEXT NOT NULL,
	[Street] TEXT NOT NULL,
	[HouseNumber] TEXT NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_Address PRIMARY KEY ([AddressId] AUTOINCREMENT)
)
;

CREATE TABLE [Team]
(
	[TeamId] INTEGER NOT NULL,
	[Name] TEXT NOT NULL,
	[Logo] TEXT NULL,
	[RegistrationDate] TEXT NOT NULL,
	[IsActive] INTEGER NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_Team PRIMARY KEY ([TeamId] AUTOINCREMENT)
)
;

CREATE TABLE [User]
(
	[UserId] INTEGER NOT NULL,
	[Email] TEXT NOT NULL,
	[EmailConfirmed] bit NOT NULL DEFAULT 0,
	[PasswordHash] TEXT NULL,
	[SecurityStamp] TEXT NULL,
	[PhoneNumber] TEXT NULL,
	[PhoneNumberConfirmed] bit NOT NULL DEFAULT 0,
	[TwoFactorEnabled] bit NOT NULL DEFAULT 0,
	[LockoutEndDateUtc] TEXT NULL,
	[LockoutEnabled] bit NOT NULL,
	[AccessFailedCount] INTEGER NOT NULL DEFAULT 0,
	[UserName] TEXT NOT NULL,
	[FirstName] TEXT NOT NULL,
	[LastName] TEXT NOT NULL,
	[Gender] TEXT NOT NULL,
    [DateOfBirth] TEXT NOT NULL,
    [RegistrationDate] TEXT NOT NULL,
	[ExternalLogin] bit NOT NULL DEFAULT 0,
	[RegistrationGUID] TEXT NULL,
	[GUIDExpirationDate] TEXT NULL,
	CONSTRAINT PK_User PRIMARY KEY ([UserId] AUTOINCREMENT)
)
;

CREATE TABLE [Role]
(
	[RoleId] INTEGER NOT NULL,
	[Name] TEXT NOT NULL,
	CONSTRAINT PK_Role PRIMARY KEY ([RoleId] AUTOINCREMENT)
)
;

CREATE TABLE [UserClaim]
(
	[UserClaimId] INTEGER NOT NULL,
	[UserId] INTEGER NOT NULL,
	[ClaimType] TEXT NOT NULL,
	[ClaimValue] TEXT NOT NULL,
	CONSTRAINT PK_UserClaim PRIMARY KEY ([UserClaimId] AUTOINCREMENT),
	CONSTRAINT FK_UserClaim_User FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
;

CREATE TABLE [UserLogin]
(
	[LoginProvider] TEXT NOT NULL,
	[ProviderKey] TEXT NOT NULL,
	[UserId] INTEGER NOT NULL,
	CONSTRAINT PK_UserLogin PRIMARY KEY ([LoginProvider], [ProviderKey], [UserId]),
	CONSTRAINT FK_UserLogin_User FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
;

CREATE TABLE [UserRole]
(
	[UserRoleId] INTEGER NOT NULL,
	[UserId] INTEGER NOT NULL,
	[RoleId] INTEGER NOT NULL,
    [IsActive] INTEGER NOT NULL,
	[TeamIdOrDefault] INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT PK_UserRole PRIMARY KEY ([UserRoleId] AUTOINCREMENT),
	CONSTRAINT FK_UserRole_User FOREIGN KEY ([UserId]) REFERENCES [User]([UserId]),
	CONSTRAINT FK_UserRole_Role FOREIGN KEY ([RoleId]) REFERENCES [Role]([RoleId])
)
;

CREATE TABLE [TourSerie]
(
	[TourSerieId] INTEGER NOT NULL,
	[Name] TEXT NOT NULL,
	[StartDate] TEXT NOT NULL,
	[EndDate] TEXT NULL,
	[Category] TEXT NULL,
	[Note] TEXT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_TourSerie PRIMARY KEY ([TourSerieId] AUTOINCREMENT)
)
;

CREATE TABLE [Tournament]
(
	[TournamentId] INTEGER NOT NULL,
	[TourSerieId] INTEGER NULL,
	[AddressId] INTEGER NULL,
	[Name] TEXT NOT NULL,
	[StartDate] TEXT NOT NULL,
	[EndDate] TEXT NOT NULL,
	[EntryFee] REAL NULL,
	[MaxNumOfTeams] INTEGER NULL,
	[Note] TEXT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_Tournament PRIMARY KEY ([TournamentId] AUTOINCREMENT),
	CONSTRAINT FK_Tournament_TournSerie FOREIGN KEY ([TourSerieId]) REFERENCES [TourSerie]([TourSerieId]),
	CONSTRAINT FK_Tournament_Address FOREIGN KEY ([AddressId]) REFERENCES [Address]([AddressId])
)
;

CREATE TABLE [TournamentPlayerStat]
(
	[TournamentPlayerStatId] INTEGER NOT NULL,
	[TournamentId] INTEGER NOT NULL,
	[PlayerId] INTEGER NOT NULL,
	[TourPoints] INTEGER NULL,
	[AttackPoints] INTEGER NULL,
	[AttackPercentage] REAL NULL,
	[ServicePoints] INTEGER NULL,
	[ServicePercentage] INTEGER NULL,
	[UnforcedErrors] INTEGER NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_TournamentPlayerStat PRIMARY KEY ([TournamentPlayerStatId] AUTOINCREMENT),
	CONSTRAINT FK_TournamentPlayerStat_Tournament FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([TournamentId]),
	CONSTRAINT FK_TournamentPlayerStat_Player FOREIGN KEY ([PlayerId]) REFERENCES [User]([UserId])
);

CREATE TABLE [PlayoffRoundCouple]
(
	[PlayoffRoundCoupleId] INTEGER NOT NULL,
    [TournamentTeam1Id] INTEGER NOT NULL,
    [TournamentTeam2Id] INTEGER NOT NULL,
    [PlayoffRound] INTEGER NOT NULL,
    [Team1Wins] INTEGER NOT NULL,
    [Team2Wins] INTEGER NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_PlayoffRoundCouple PRIMARY KEY ([PlayoffRoundCoupleId] AUTOINCREMENT),
	CONSTRAINT FK_PlayoffRoundCouple_TournamentTeam1 FOREIGN KEY ([TournamentTeam1Id]) REFERENCES [TournamentTeam]([TournamentTeamId]),
	CONSTRAINT FK_PlayoffRoundCouple_TournamentTeam2 FOREIGN KEY ([TournamentTeam2Id]) REFERENCES [TournamentTeam]([TournamentTeamId])
);

CREATE TABLE [TournamentTeam]
(
	[TournamentTeamId] INTEGER NOT NULL,
	[TournamentId] INTEGER NOT NULL,
	[TeamId] INTEGER NOT NULL,
	[BasicGroupName] TEXT NULL,
	[RegistrationDate] TEXT NOT NULL,
	[EntryFeePaid] bit NOT NULL DEFAULT 0,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_TournamentTeam PRIMARY KEY ([TournamentTeamId] AUTOINCREMENT),
	CONSTRAINT FK_TournamentTeam_Tournament FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([TournamentId]),
	CONSTRAINT FK_TournamentTeam_Team FOREIGN KEY ([TeamId]) REFERENCES [Team]([TeamId])
);

CREATE TABLE [TournamentTeamStat]
(
	[TournamentTeamStatId] INTEGER NOT NULL,
	[TournamentTeamId] INTEGER NOT NULL,
	[TournamentPhase] INTEGER NOT NULL DEFAULT 1,
	[PhasePoints] INTEGER NOT NULL,
	[Wins] INTEGER NOT NULL,
	[Losts] INTEGER NOT NULL,
	[Ties] INTEGER NOT NULL,
	[SetsWon] INTEGER NOT NULL,
	[SetsLost] INTEGER NOT NULL,
	[ScorePlus] INTEGER NOT NULL,
	[ScoreMinus] INTEGER NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_TournamentTeamStat PRIMARY KEY ([TournamentTeamStatId] AUTOINCREMENT),
	CONSTRAINT FK_TournamentTeamStat_TournamentTeam FOREIGN KEY ([TournamentTeamId]) REFERENCES [TournamentTeam]([TournamentTeamId])
)
;

CREATE TABLE [Match]
(
	[MatchId] INTEGER NOT NULL,
	[HomeTeamId] INTEGER NOT NULL,
	[AwayTeamId] INTEGER NOT NULL,
    [TournamentId] INTEGER NULL,
    [TournamentPhase] INTEGER NOT NULL DEFAULT 1,
    [WinnerId] INTEGER NULL,
	[RefereeId] INTEGER NULL,
    [MatchDate] TEXT NULL,
	[PlayoffRoundCoupleId] INTEGER NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_Match PRIMARY KEY ([MatchId] AUTOINCREMENT),
	CONSTRAINT FK_Match_Tournament FOREIGN KEY ([TournamentId]) REFERENCES [Tournament]([TournamentId]),
	CONSTRAINT FK_Match_HomeTeam FOREIGN KEY ([HomeTeamId]) REFERENCES [Team]([TeamId]),
	CONSTRAINT FK_Match_AwayTeam FOREIGN KEY ([AwayTeamId]) REFERENCES [Team]([TeamId]),
	CONSTRAINT FK_Match_PlayoffRoundCouple FOREIGN KEY ([PlayoffRoundCoupleId]) REFERENCES [PlayoffRoundCouple]([PlayoffRoundCoupleId])
)
;

CREATE TABLE [MatchSetScore]
(
	[MatchSetScoreId] INTEGER NOT NULL,
	[MatchId] INTEGER NOT NULL,
	[HomeTeamScore] INTEGER NOT NULL,
	[AwayTeamScore] INTEGER NOT NULL,
	[SetOrder] INTEGER NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_MatchSetScore PRIMARY KEY ([MatchSetScoreId] AUTOINCREMENT),
	CONSTRAINT FK_MatchSetScore_Match FOREIGN KEY ([MatchId]) REFERENCES [Match]([MatchId])
)
;

CREATE TABLE [TeamPlayer]
(
	[TeamPlayerId] INTEGER NOT NULL,
	[TeamId] INTEGER NOT NULL,
	[PlayerId] INTEGER NOT NULL,
	[LastChange] TEXT NOT NULL,
	[ChangedBy] INTEGER NULL,
	CONSTRAINT PK_TeamPlayer PRIMARY KEY ([TeamPlayerId] AUTOINCREMENT),
	CONSTRAINT FK_TeamPlayer_Team FOREIGN KEY ([TeamId]) REFERENCES [Team]([TeamId])
)
;

INSERT INTO [Role] ([Name]) VALUES ('Host');
INSERT INTO [Role] ([Name]) VALUES ('Player');
INSERT INTO [Role] ([Name]) VALUES ('TeamAdmin');
INSERT INTO [Role] ([Name]) VALUES ('Admin');
