//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLO128.D3ORM.Sample.Domain.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KLO128.D3ORM.Sample.Domain.Shared.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player {0} does not exist..
        /// </summary>
        public static string err002 {
            get {
                return ResourceManager.GetString("err002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team {0} already exists..
        /// </summary>
        public static string err003 {
            get {
                return ResourceManager.GetString("err003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team {0} was not found..
        /// </summary>
        public static string err004 {
            get {
                return ResourceManager.GetString("err004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player {0} was not found in the team {1}..
        /// </summary>
        public static string err005 {
            get {
                return ResourceManager.GetString("err005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player {0} already exists..
        /// </summary>
        public static string err006 {
            get {
                return ResourceManager.GetString("err006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament {0} was not found..
        /// </summary>
        public static string err007 {
            get {
                return ResourceManager.GetString("err007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match {0} was not found..
        /// </summary>
        public static string err008 {
            get {
                return ResourceManager.GetString("err008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process empty filter..
        /// </summary>
        public static string err009 {
            get {
                return ResourceManager.GetString("err009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match set of order {0} was not found..
        /// </summary>
        public static string err010 {
            get {
                return ResourceManager.GetString("err010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team {0} is not registered into the tournament {1}..
        /// </summary>
        public static string err011 {
            get {
                return ResourceManager.GetString("err011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team {0} has already been signed up to the tournament {1}..
        /// </summary>
        public static string err012 {
            get {
                return ResourceManager.GetString("err012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string err013 {
            get {
                return ResourceManager.GetString("err013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password.
        /// </summary>
        public static string err014 {
            get {
                return ResourceManager.GetString("err014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Basic Groups: The number of Basic groups shoud be a pair number or equal to 1..
        /// </summary>
        public static string err015 {
            get {
                return ResourceManager.GetString("err015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playoff first round couples already added for the tournament: {0}.
        /// </summary>
        public static string err016 {
            get {
                return ResourceManager.GetString("err016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups have already been drawn for the tournament: {0}.
        /// </summary>
        public static string err017 {
            get {
                return ResourceManager.GetString("err017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches have already been drawn for the tournament: {0}.
        /// </summary>
        public static string err018 {
            get {
                return ResourceManager.GetString("err018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address {0} was not found..
        /// </summary>
        public static string err019 {
            get {
                return ResourceManager.GetString("err019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Team Stats not found for the team {0}..
        /// </summary>
        public static string err020 {
            get {
                return ResourceManager.GetString("err020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        public static string err401 {
            get {
                return ResourceManager.GetString("err401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not match {1}..
        /// </summary>
        public static string msgCompareFailed {
            get {
                return ResourceManager.GetString("msgCompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match the required pattern..
        /// </summary>
        public static string msgRegexFailed {
            get {
                return ResourceManager.GetString("msgRegexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string msgRequired {
            get {
                return ResourceManager.GetString("msgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string length is not the range of {1} to {2} in the field {0}..
        /// </summary>
        public static string msgStringLengthFailed {
            get {
                return ResourceManager.GetString("msgStringLengthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player {0} you want to add is already in the team {1}..
        /// </summary>
        public static string warn001 {
            get {
                return ResourceManager.GetString("warn001", resourceCulture);
            }
        }
    }
}
